services:
  # Spring Boot application
  app:
    build: .
    ports:
      - "8080:8080"
  
  # SonarQube Server
  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  # Jenkins Server
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data:
